sudo: required
language: generic

services:
  - docker

before_install:
 - docker build -t emaynewrelic/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true emaynewrelic/react-test npm test

after_success:
  - docker build -t emaynewrelic/multi-client ./client
  - docker build -t emaynewrelic/multi-nginx ./nginx
  - docker build -t emaynewrelic/multi-server ./server
  - docker build -t emaynewrelic/multi-worker ./worker
  # Log in to the docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  - echo $DOCKER_ID
  # Take those images and push them to docker hub
  - docker push emaynewrelic/multi-client
  - docker push emaynewrelic/multi-nginx
  - docker push emaynewrelic/multi-server
  - docker push emaynewrelic/multi-worker
